version: "3.9"
services:
  apiserver:
    build:
      context: ./
      dockerfile: ./docker/api.Dockerfile
    image: "tanaya-api-server:latest"
    volumes:
      - ./:/tanayaPortfolio
    expose:
      - 8000
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      - "db"
    restart: unless-stopped

  webserver:
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    image: "tanaya-webserver-server:latest"
    volumes:
      - ./:/tanayaPortfolio
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      - "apiserver"
    restart: unless-stopped

  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    image: "tanaya-db-server:latest"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    restart: unless-stopped
volumes:
  postgres_data: