version: "3.9"
services:
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    image: "tanaya-db-server:latest"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5428:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    restart: unless-stopped
volumes:
  postgres_data: